mongodb:
  image: mongo:latest
  volumes:
   - "/var/lib/mongodb:/var/lib/mongodb"
  ports:
   - "27017:27017"

api:
  image: tageler/api:latest
  links:
   - mongodb
  environment:
   VIRTUAL_HOST: api.tageler.ch
  
